#!/bin/bash

XDG_CONFIG_DIR="$HOME/.config/"
LOG_FILE="/tmp/toggle-theme.log"


# Function to log messages
log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> "$LOG_FILE"
}

log "starting script"
function gtk_dark() {
	gsettings set org.gnome.desktop.interface color-scheme prefer-dark
	gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark
}

function gtk_light() {
	gsettings set org.gnome.desktop.interface color-scheme prefer-light
	gsettings set org.gnome.desktop.interface gtk-theme Adwaita
}

function kitty_apply() {
	ss -l -x | grep 'kitty' | awk '{ print($5) }' | xargs -I % kitten @ load-config --to unix:%
    kitty @ set-colors --all "$XDG_CONFIG_DIR/kitty/colors.conf"
}

function kitty_dark() {
	ln --symbolic --force "$XDG_CONFIG_DIR/kitty/sakura.conf" "$XDG_CONFIG_DIR/kitty/colors.conf"
}

function kitty_light() {
	ln --symbolic --force "$XDG_CONFIG_DIR/kitty/tokyonight_day.conf" "$XDG_CONFIG_DIR/kitty/colors.conf"
}

function nvim_dark() {
    echo 'return { flavour = "mocha" }' > "$XDG_CONFIG_DIR/nvim/theme.lua"
}

function nvim_light() {
    echo 'return { flavour = "latte" }' > "$XDG_CONFIG_DIR/nvim/theme.lua"
}

function mako_apply() {
	makoctl reload
    log "mako reload"
}

function mako_dark() { 
	cat "$XDG_CONFIG_DIR/mako/config-base" "$XDG_CONFIG_DIR/mako/themes/catppuccin-mocha/catppuccin-mocha-flamingo" > "$XDG_CONFIG_DIR/mako/config"
    log "mako dark"
}

function mako_light() {
	cat "$XDG_CONFIG_DIR/mako/config-base" "$XDG_CONFIG_DIR/mako/themes/catppuccin-latte/catppuccin-latte-flamingo" > "$XDG_CONFIG_DIR/mako/config"
    log "mako light"
}

function sway_apply() {
	swaymsg reload
}

function sway_dark() {
	ln --symbolic --force "$XDG_CONFIG_DIR/sway/colors-catpuccin-mocha" "$XDG_CONFIG_DIR/sway/colors"
}

function sway_light() {
	ln --symbolic --force "$XDG_CONFIG_DIR/sway/colors-catpuccin-latte" "$XDG_CONFIG_DIR/sway/colors"
}

function wofi_dark() {
	ln --symbolic --force "$XDG_CONFIG_DIR/wofi/config-catpuccin-mocha" "$XDG_CONFIG_DIR/wofi/style.css"
}

function wofi_light() {
	ln --symbolic --force "$XDG_CONFIG_DIR/wofi/config-catpuccin-latte" "$XDG_CONFIG_DIR/wofi/style.css"
}

STATE_FILE="$HOME/.local/state/theme-toggle/state.json"

function setup() {
	if [ -f "$STATE_FILE" ]
	then
		return
	fi

	mkdir -p "$(dirname $STATE_FILE)"
	echo '{"theme": "dark"}' > "$STATE_FILE"
}

function set_theme() {
	state="$(cat $STATE_FILE)"
	echo "$state" | jq --arg t "$theme" '.theme = $t' > "$STATE_FILE"
}


function get_theme() {
	current="$(jq -r '.theme' "$STATE_FILE")"
	echo "$current"
}

theme=""
function process_args() {
	if [ -z "$1" ]
	then
		echo "Please provide the argument 'dark', 'light' or 'switch'"
		exit 1
	fi

	if [ "$1" == "light" ] || [ "$1" == "dark" ]
	then
		theme="$1"
	elif [ "$1" == "switch" ]; then
		current="$(get_theme)"
		theme="dark"
		if [ "$current" == "dark" ]
		then
			theme="light"
		fi
		echo "$theme"
	else
		echo "Unkown argument, please provide the argument 'dark', 'light' or 'switch'"
		exit 1
	fi
}

function main() {
	for f in $(declare -F | grep "$theme" | awk '{ print($3) }')
	do 
		echo "$f"
		"$f"
	done

	for f in $(declare -F | grep 'apply' | awk '{ print($3) }')
	do 
		echo "$f"
		"$f"
	done
}

setup
process_args "$@"
main
set_theme
